name: hoopsim
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - pip
  - pandas>=2.0
  - numpy>=1.24
  - matplotlib>=3.7
  - scikit-learn>=1.3
  - tqdm>=4.66
  - pip:
      - basketball-reference-scraper>=1.1.2
      - nba_api>=1.4
      - streamlit>=1.36
